[package]
name = "thinkmorse"
version = "0.1.0"
authors = ["richusx <me@richusx.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
morse = "0.1.0"